"use client"
import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Slider from "./_components/Slider";
import { Toaster } from "@/components/ui/sonner";
import { usePathname } from "next/navigation";
import { UpdateCartContext } from "./_context/UpdateCartContex";
import { useState } from "react";
import { PayPalScriptProvider } from "@paypal/react-paypal-js";

const inter = Outfit({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const params=usePathname();
  const [updateCart,setUpdateCart] = useState(false);
  const showHeader=params=='/sign-in'||params=='/create-account'?false:true;

  return (
    <PayPalScriptProvider options={{ clientId: `${process.env.NEXT_PUBLIC_PAYPAL_CLIENT_ID}` }}>
            
        
    <html lang="en">
      <body className={inter.className}>
      {/* <Header/> */}
      <UpdateCartContext.Provider value={{updateCart,setUpdateCart}}>
      {showHeader&&<Header/>}
      {children}
      <Toaster />
      </UpdateCartContext.Provider>
      
      {/* <Slider/> */}
      </body>
    </html>
    </PayPalScriptProvider>
  );
}
